server:
  port: 8887

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8887/eureka/

spring:
  application:
    name: PRO-MS-FILE
