server:
  port: 7009

spring:
  application:
    name: MICRO-SERVICE-ZUUL

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8788/eureka/

zuul:
  routes:
    #满足/api 开头的请求都被分发到 serviceId 对应的服务
    microservice-ms-user:
      #微服务名称
      serviceId: MICRO-SERVICE-USER
      path: /api/**
    microservice-ms-file:
      serviceId: MICRO-SERVICE-FILE
      path: /file/**

ribbon:
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600