server:
  port: 8898
  servlet:
    context-path: /api

spring:
  application:
    name: MICRO-SERVICE-WEB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8788/eureka/

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000