server:
  port: 8886


eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8788/eureka/

spring:
  application:
    name: MICRO-SERVICE-USER

#ribbon:
#  eureka:
#    enabled: true
